#!/usr/bin/python3
"""
A simple, stateful REPL, or read eval print loop.
"""
import sys
sys.path.append("src/")

# REPL history
try: import readline
except: pass

from pypethon import stdlib
from pypethon import exceptions
from pypethon.interpreter import evaluate

read = input
state = stdlib.build()


if __name__ == "__main__":
    while True:
        try:
            # read, eval, print
            value = evaluate(read("> "), state)
            if value:
                print(value)
            # loop ...
        except exceptions.SyntaxException as e:
            print(e)
        except KeyboardInterrupt:
            exit(0)
        except Exception as e:
            print(e)
